import xml.etree.ElementTree as ET
import os

# Guardar a pasta que contem as ruas
xml_folder = "/Users/jony/Documents/GitHub/EngWeb2024/TPC1/MapaRuas-materialBase/texto/"

# Guardar todos os arquivos em xml_files
xml_files = [f for f in os.listdir(xml_folder) if f.endswith(".xml")]

# Ordenar a lista de nomes dos ficheiros XML alfabeticamente
xml_files.sort()

preHTML = f"""
<!DOCTYPE html>
<html>

    <head>
        <title>Lista das ruas de Braga</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8"/> 
        <link rel="stylesheet" href="w3.css">
    </head>

<body>

    <div class="w3-card-4">

        <header class="w3-container w3-blue-gray">
          <h3>Lista das ruas de Braga</h3>
        </header>
        
        <div class="w3-container">
            <ul class="w3-ul w3-card-4" style="width:50%">"""

posHTML = f"""
            </ul>
        </div>
        
        <footer class="w3-container w3-blue-gray">
            <h5>Generated by RuaApp::EngWeb2024::A100740 </h5>
        </footer>        
    </div> 

</body>

</html>
"""

def remove_spaces(text):
    return text.replace(" ", "")
    
conteudo = ""

for e in xml_files:
    tree = ET.parse(os.path.join(xml_folder, e))
    myroot = tree.getroot()
    nome = remove_spaces(myroot[0].find("nome").text)
    conteudo += f"""
        <li>
            <a href="{nome}.html"> <!-- faz referencia à pagina individual do nome --> 
            {e}</a> <!-- imprime o nome do ficheiro .xml --> 
        </li>
    """
    
pagHTML = preHTML + conteudo + posHTML
f = open("RuaSite/Index.html", 'w')
f.write(pagHTML)
f.close()