const http = require('http');
const fs = require('fs');
const url = require('url');
var axios = require('axios')

http.createServer((req, res) => {
    var path = url.parse(req.url).pathname;
    var regex = /\/c\d{1,3}/

    console.log(req.method + '' + req.url)

    if (path == '/'){
        axios.get("http://localhost:3000/cidades?_sort=nome")
        .then(resp => {
            res.writeHead(200, {'Contnt-Type' : 'text/html; charset=utf-8'})
            res.write(handleHomePage(resp.data))
            res.end()
        })
        .catch(erro => {
            res.writeHead(500, {'Contnt-Type' : 'text/html; charset=utf-8'})
            res.write("<p> Ocorreu um erro: " + erro + "</p>")
            res.end()
        })
    }else if (regex.test(path)) {
        fs.readFile('cidades' + path + '.html', 'utf8', (erro, dados) => {
            if (erro) {
                res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
                res.write('<p> Página não encontrada </p>');
                res.end();  // Aqui você encerra a resposta
                return;
            }
    
            var cidadeId = path.substring(1); // Remover a barra inicial
    
            axios.get("http://localhost:3000/cidades?_sort=nome")
                .then(resp => {
                    var linksOutrasCidades = resp.data
                        .filter(outraCidade => outraCidade.id !== cidadeId)
                        .map(outraCidade => `<li><a href="/${outraCidade.id}">${outraCidade.nome}</a></li>`)
                        .join('');
    
                    // Adicionar links para outras cidades ao conteúdo
                    var conteudoModificado = dados.replace('<!-- OUTRAS_CIDADES -->', linksOutrasCidades);
    
                    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
                    res.write(conteudoModificado);  // Aqui você escreve na resposta
                    res.end();  // Aqui você encerra novamente
                })
                .catch(erro => {
                    res.writeHead(500, { 'Content-Type': 'text/html; charset=utf-8' });
                    res.write('<p> Ocorreu um erro ao obter as cidades </p>');
                    res.end();  // Aqui você encerra novamente
                });
        });
    } else if (path == '/w3.css'){
        fs.readFile("w3.css", (erro,dados) => {
            res.writeHead(200, {'Contnt-Type' : 'text/css; charset=utf-8'})
            res.write(dados)
            res.end()
        })
    }else{
        res.writeHead(400, {'Contnt-Type' : 'text/html; charset=utf-8'})
        res.write('<p> Erro: Pedido não suportado </p>')
        res.write('<pre>' + req.url +'</pre>')
        res.end()
    }
}).listen(7777);


function handleHomePage(index) {
    // Construir a página principal
    var paginaPrincipalHTML = `
        <!DOCTYPE html>
        <html lang="pt-br">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Página Principal</title>
            <style>
                body {
                    font-family: 'Arial', sans-serif;
                }
                h3 {
                    color: #607D8B;
                }
                ul {
                    list-style-type: none;
                    padding: 0;
                }
                li {
                    margin-bottom: 10px;
                }
                h5 {
                    color: #607D8B;
                }
            </style>
        </head>
        <body>
            <div>
                <h3>Cidades</h3>
                <ul> `
            index.forEach(city => {
                paginaPrincipalHTML += `
                    <li>
                    <a href="/${city.id}">${city.nome}</a>
                    </li>
                `
            });
        paginaPrincipalHTML += `</ul>
                <h5>Generated by CidadeApp::EngWeb2024::A100740</h5>
            </div>
        </body>
        </html>
    `
    return paginaPrincipalHTML
}

